# Generated by Django 5.2.11 on 2026-02-13 14:32

import django.db.models.deletion
import submissions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0003_task_due_date_task_points_task_task_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to=submissions.models.submission_audio_path, validators=[submissions.models.validate_audio_file])),
                ('status', models.CharField(choices=[('submitted', 'Soumis'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='submitted', max_length=10)),
                ('admin_feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True, default=submissions.models.default_expires_at)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('awarded_points', models.PositiveIntegerField(blank=True, null=True)),
                ('points_awarded_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tasks.task')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('task', 'student'), name='unique_submission_per_task_student')],
            },
        ),
    ]
