# Generated by Django 5.2.11 on 2026-02-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Points awarded for completing this task'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('recitation', 'Récitation'), ('memorization', 'Mémorisation'), ('other', 'Autre')], default='other', max_length=20),
        ),
    ]
