# Generated by Django 5.2.11 on 2026-02-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_due_date_task_points_task_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("student", "Élève"), ("teacher", "Professeur")],
                default="student",
                max_length=10,
            ),
        ),
    ]
