# Generated by Django 5.2.11 on 2026-02-20 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tasks', '0004_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('student', 'Étudiant'), ('group', 'Groupe')], max_length=50)),
                ('entity_id', models.IntegerField()),
                ('conflicts', models.JSONField(help_text='Liste des conflits détectés')),
                ('resolved_changes', models.JSONField(help_text='Changements après résolution')),
                ('resolution_strategy', models.CharField(default='admin_priority', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts_as_admin', to=settings.AUTH_USER_MODEL)),
                ('teacher_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts_as_teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Conflit',
                'verbose_name_plural': 'Logs de Conflits',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GroupExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slot', models.CharField(choices=[('8h45', '8h45'), ('10h45', '10h45')], max_length=10)),
                ('max_students', models.IntegerField(default=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='auth.group')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extension de Groupe',
                'verbose_name_plural': 'Extensions de Groupes',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, help_text='Niveau de mémorisation (ex: Juz 15)', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('graduated', 'Diplômé')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes internes Admin/Prof')),
                ('objectives', models.TextField(blank=True, help_text="Objectifs de l'élève")),
                ('restrictions', models.TextField(blank=True, help_text='Restrictions ou règles spéciales')),
                ('special_case', models.JSONField(blank=True, default=dict, help_text='الحالة الخاصة بالطالب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Étudiant',
                'verbose_name_plural': 'Profils Étudiants',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_group', 'Création de groupe'), ('rename_group', 'Renommage de groupe'), ('delete_group', 'Suppression de groupe'), ('assign_student', 'Assignation élève'), ('update_profile', 'Modification profil'), ('assign_teacher', 'Assignation professeur')], max_length=50)),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'Audit",
                'verbose_name_plural': "Journaux d'Audit",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='tasks_audit_timesta_a48392_idx'), models.Index(fields=['admin_user', '-timestamp'], name='tasks_audit_admin_u_72adcc_idx'), models.Index(fields=['target_user', '-timestamp'], name='tasks_audit_target__c33ae3_idx'), models.Index(fields=['action', '-timestamp'], name='tasks_audit_action_76756f_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserGroupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_changes_made', to=settings.AUTH_USER_MODEL)),
                ('new_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_members', to='auth.group')),
                ('old_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_members', to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de Groupe',
                'verbose_name_plural': 'Historiques de Groupes',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['user', '-changed_at'], name='tasks_userg_user_id_101904_idx'), models.Index(fields=['new_group', '-changed_at'], name='tasks_userg_new_gro_e0a5cc_idx')],
            },
        ),
    ]
